---
title: "Native COSMOS analysis"
author: "Pascal Lafrenz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Infer native activity scores and COSMOS network 

Here, we repeat the analysis without MOFA to be able to compare this approach with the MOFA-COSMOS pipeline.

```{r Loading packages, message=FALSE}
library(cosmosR)
library(MOFA2)
library(readr)
library(ggplot2)
library(ggfortify)
library(dplyr)
library(reshape2)
library(liana)
library(decoupleR)
library(moon)
library(pheatmap)
library(gridExtra)
library(liana)
library(GSEABase)
library(tidyr)
library(RCy3)
```

```{r COSMOS, eval=FALSE}
# Make native COSMOS

## Get RNA raw values
RNA <- as.data.frame(read_csv("data/RNA/RNA_log2_FPKM_clean.csv"))
rownames(RNA) <- RNA[,1]
RNA <- RNA[,-1]

## Load metabolomics
metab <- as.data.frame(read_csv("data/metabolomic/metabolomic_clean_vsn.csv"))
rownames(metab) <- metab[,1]
metab <- metab[,-1]

## Load LIANA (receptor and ligand) consensus network
ligrec_ressource <- distinct(liana::decomplexify(liana::select_resource("Consensus")[[1]]))
ligrec_geneset <- ligrec_ressource[,c("source_genesymbol","target_genesymbol")]
ligrec_geneset$set <- paste(ligrec_geneset$source_genesymbol, ligrec_geneset$target_genesymbol, sep = "___")
ligrec_geneset <- reshape2::melt(ligrec_geneset, id.vars = "set")[,c(3,1)]
names(ligrec_geneset)[1] <- "gene"
ligrec_geneset$mor <- 1
ligrec_geneset$likelihood <- 1
ligrec_geneset <- distinct(ligrec_geneset)

## Load Dorothea (TF) network
dorothea_df <- decoupleR::get_dorothea()

## Load meta footprint analysis (moon) regulatory network 
moon_regulons <- moon::build_moon_regulons()

## Calculate activity scores (mOOn, TF, LigRec) per cell line
lig_rec_scores_native <- list()
moon_scores_native <- list()
dorothea_scores_native <- list()
cosmos_input <- list()

for(i in c("SF-539", "MOLT-4")) { 
  RNA_sample_native <- RNA[,i]
  names(RNA_sample_native) <- rownames(RNA)
  RNA_sample_native <- RNA_sample_native[!is.na(RNA_sample_native)]
  
  metab_sample_native <- metab[,i]
  names(metab_sample_native) <- rownames(metab)
  metab_sample_native <- metab_sample_native[!is.na(metab_sample_native)]
  
  # Calculate regulatory activities from Receptor and Ligand network
  ligrec_high_vs_low <- run_wmean(mat = as.matrix(RNA_sample_native), network = ligrec_geneset, times = 1000, .source = set, .target = gene, minsize = 2, seed = 42) 
  ligrec_high_vs_low <- ligrec_high_vs_low[ligrec_high_vs_low$statistic == "norm_wmean",]
  ligrec_high_vs_low_vector <- ligrec_high_vs_low$score
  names(ligrec_high_vs_low_vector) <- ligrec_high_vs_low$source
  
  rec_inputs <- ligrec_high_vs_low_vector
  names(rec_inputs) <- gsub(".+___","",names(rec_inputs))
  rec_inputs <- tapply(rec_inputs, names(rec_inputs), mean)
  receptors <- names(rec_inputs)
  rec_inputs <- as.numeric(rec_inputs)
  names(rec_inputs) <- receptors
  
  lig_rec_scores_native[[i]] <- rec_inputs#[names(rec_inputs) %in% interesting_nodes$name]
  
  lig_inputs <- ligrec_high_vs_low_vector
  names(lig_inputs) <- gsub("___.+","",names(lig_inputs))
  lig_inputs <- tapply(lig_inputs, names(lig_inputs), mean)
  ligands <- names(lig_inputs)
  lig_inputs <- as.numeric(lig_inputs)
  names(lig_inputs) <- ligands
  
  lig_rec_scores_native[[i]] <- c(lig_rec_scores_native[[i]],lig_inputs)
  
  # Calculate regulatory activities from TF network
  TF_high_vs_low <- run_wmean(mat = as.matrix(RNA_sample_native), network = dorothea_df, times = 1000, minsize = 10, seed = 42)
  TF_high_vs_low <- TF_high_vs_low[TF_high_vs_low$statistic == "norm_wmean",]
  TF_high_vs_low_vector <- TF_high_vs_low$score
  names(TF_high_vs_low_vector) <- TF_high_vs_low$source
  
  dorothea_scores_native[[i]] <- TF_high_vs_low_vector 
  
  # Prepare moon analysis input
  TF_high_vs_low <- as.data.frame(TF_high_vs_low[,c(2,4)])
  row.names(TF_high_vs_low) <- TF_high_vs_low[,1]
  
  # Calculate TF regulatory activities from moon network
  moon_high_vs_low <- run_wmean(mat = as.matrix(TF_high_vs_low[,-1,drop = F]), network = moon_regulons, times = 1000, minsize = 10, seed = 42)
  moon_high_vs_low <- moon_high_vs_low[moon_high_vs_low$statistic == "norm_wmean",]
  moon_high_vs_low_vector <- moon_high_vs_low$score
  names(moon_high_vs_low_vector) <- moon_high_vs_low$source
  moon_high_vs_low_vector <- moon_high_vs_low_vector[!(names(moon_high_vs_low_vector) %in% names(TF_high_vs_low_vector))] #exclude all found in TF activity estimation, only keep others to prevent overrepresentation
  
  moon_scores_native[[i]] <- moon_high_vs_low_vector
  
  cosmos_input[[i]][["RNA"]] <- RNA_sample_native
  cosmos_input[[i]][["metab"]] <- metab_sample_native
  cosmos_input[[i]][["moon_scores_native"]] <- moon_high_vs_low_vector
  cosmos_input[[i]][["dorothea_scores_native"]] <- TF_high_vs_low_vector
  cosmos_input[[i]][["lig_rec_scores_native"]] <- c(rec_inputs,lig_inputs)
}

save(cosmos_input, file = "data/cosmos/native/cosmos_input.RData")

# load("data/cosmos/native/cosmos_input.RData")


for (cell_line in c("SF-539", "MOLT-4")) {

  RNA <- cosmos_input[[cell_line]]$RNA
  metab <- cosmos_input[[cell_line]]$metab
  # proteo <- cosmos_input[[cell_line]]$proteo
  moon_scores_native <- cosmos_input[[cell_line]]$moon_scores_native
  dorothea_scores_native <- cosmos_input[[cell_line]]$dorothea_scores_native
  lig_rec_scores_native <- cosmos_input[[cell_line]]$lig_rec_scores_native
  
  dorothea_scores_native <- dorothea_scores_native[abs(dorothea_scores_native) > 2]
  metab <- metab[abs(metab) > 2]
  moon_scores_native <- moon_scores_native[abs(moon_scores_native) > 2]
  lig_rec_scores_native <- lig_rec_scores_native[abs(lig_rec_scores_native) > 2]
  
  metab_to_HMDB <- as.data.frame(
    read_csv("data/metabolomic/MetaboliteToHMDB.csv"))
  metab_to_HMDB <- metab_to_HMDB[metab_to_HMDB$common %in% names(metab),]
  metab <- metab[metab_to_HMDB$common]
  names(metab) <- metab_to_HMDB$HMDB
  
  metab <- cosmosR::prepare_metab_inputs(metab, compartment_codes = c("m","c"))
  
  rec_inputs <- lig_rec_scores_native
  names(rec_inputs) <- gsub(".+___","",names(rec_inputs))
  rec_inputs <- tapply(rec_inputs, names(rec_inputs), mean)
  receptors <- names(rec_inputs)
  rec_inputs <- as.numeric(rec_inputs)
  names(rec_inputs) <- receptors
  
  moon_scores_native <- moon_scores_native[!(names(moon_scores_native) %in% names(rec_inputs))]
  
  data("meta_network")
  

  upstream_inputs <- c(rec_inputs,moon_scores_native)
  downstream_inputs <- c(metab, dorothea_scores_native)
  
  upstream_inputs_filtered <- cosmosR:::filter_input_nodes_not_in_pkn(upstream_inputs, meta_network)
  downstream_inputs_filtered <- cosmosR:::filter_input_nodes_not_in_pkn(downstream_inputs, meta_network)
  
  rec_to_TF_cosmos_input <- list(upstream_inputs_filtered, downstream_inputs_filtered)
  save(rec_to_TF_cosmos_input, file = paste0("data/cosmos/native/rec_to_TF_cosmos_input_",cell_line,".Rdata"))
  
  my_options <- default_CARNIVAL_options(solver = "cplex")
  my_options$solverPath <- "/Applications/CPLEX_Studio221/cplex/bin/x86-64_osx/cplex"
  my_options$solver <- "cplex"
  my_options$mipGAP <- 0.05
  my_options$threads <- 2
  my_options$timelimit <- 360
  my_options$limitPop <- 1000
  
  
  
  pre_run_rec_to_TF <- preprocess_COSMOS_signaling_to_metabolism(meta_network = meta_network,
                                                                 signaling_data = upstream_inputs_filtered,
                                                                 metabolic_data = downstream_inputs_filtered,
                                                                 diff_expression_data = RNA,
                                                                 maximum_network_depth = 4,
                                                                 remove_unexpressed_nodes = T,
                                                                 filter_tf_gene_interaction_by_optimization = T,
                                                                 CARNIVAL_options = my_options)
  my_options$mipGAP <- 0.05
  my_options$threads <- 2
  my_options$timelimit <- 720
  my_options$limitPop <- 1000
  
  run_rec_to_TF <- run_COSMOS_signaling_to_metabolism(data = pre_run_rec_to_TF,
                                                      CARNIVAL_options = my_options)
  
  save(run_rec_to_TF, file = paste0("results/cosmos/native/run_rec_to_TF_",cell_line,".Rdata"))
  
  # load(paste0("results/cosmos/native/run_rec_to_TF_",cell_line,".Rdata"))
  
  SIF_rec_to_TF <- as.data.frame(run_rec_to_TF$weightedSIF)
  SIF_rec_to_TF <- SIF_rec_to_TF[which(SIF_rec_to_TF$Weight != 0),]
  
  ATT_rec_to_TF <- as.data.frame(run_rec_to_TF$nodesAttributes)
  colnames(ATT_rec_to_TF)[1] <- "Nodes"
  ATT_rec_to_TF$measured <- ifelse(ATT_rec_to_TF$NodeType %in% c("M","T","S","P"),1,0)
  ATT_rec_to_TF$Activity <- ATT_rec_to_TF$AvgAct
  ATT_rec_to_TF <- ATT_rec_to_TF[ATT_rec_to_TF$AvgAct != 0,]
  
  res_mofa_rec_to_TF <- list(SIF_rec_to_TF,ATT_rec_to_TF)
  save(res_mofa_rec_to_TF, file = paste0("results/cosmos/native/res_mofamoon_rec_to_TFmet_",cell_line,".Rdata"))
  write_csv(SIF_rec_to_TF, file = paste0("results/cosmos/native/SIF_res_mofamoon_rec_to_TFmet_",cell_line,".csv"))
  write_csv(ATT_rec_to_TF, file = paste0("results/cosmos/native/ATT_res_mofamoon_rec_to_TFmet_",cell_line,".csv"))
  
  lig_inputs <- lig_rec_scores_native
  names(lig_inputs) <- gsub("___.+","",names(lig_inputs))
  lig_inputs <- tapply(lig_inputs, names(lig_inputs), mean)
  ligands <- names(lig_inputs)
  lig_inputs <- as.numeric(lig_inputs)
  names(lig_inputs) <- ligands
  
  upstream_inputs <- c(dorothea_scores_native, moon_scores_native)
  downstream_inputs <- c(lig_inputs)
  
  upstream_inputs_filtered <- cosmosR:::filter_input_nodes_not_in_pkn(upstream_inputs, meta_network)
  downstream_inputs_filtered <- cosmosR:::filter_input_nodes_not_in_pkn(downstream_inputs, meta_network)
  
  TF_to_lig_cosmos_input <- list(upstream_inputs_filtered, downstream_inputs_filtered)
  save(TF_to_lig_cosmos_input, file = paste0("data/cosmos/native/TF_to_lig_cosmos_input_",cell_line,".Rdata"))
  
  my_options$mipGAP <- 0.05
  my_options$threads <- 2
  my_options$timelimit <- 360
  my_options$limitPop <- 1000
  
  pre_run_TF_to_lig <- preprocess_COSMOS_signaling_to_metabolism(meta_network = meta_network, 
                                                                 signaling_data = upstream_inputs_filtered,
                                                                 metabolic_data = downstream_inputs_filtered,
                                                                 diff_expression_data = RNA,
                                                                 maximum_network_depth = 4,
                                                                 remove_unexpressed_nodes = T,
                                                                 filter_tf_gene_interaction_by_optimization = T,
                                                                 CARNIVAL_options = my_options)
  
  my_options$mipGAP <- 0.05
  my_options$threads <- 4
  my_options$timelimit <- 720
  my_options$limitPop <- 1000
  
  run_TF_to_lig <- run_COSMOS_signaling_to_metabolism(data = pre_run_TF_to_lig,
                                                      CARNIVAL_options = my_options)
  
  save(run_TF_to_lig, file = paste0("results/cosmos/native/run_TF_to_lig_",cell_line,".Rdata"))
  
  # load(paste0("results/cosmos/native/run_TF_to_lig_",cell_line,".Rdata"))
  
  SIF_TF_to_lig <- as.data.frame(run_TF_to_lig$weightedSIF)
  SIF_TF_to_lig <- SIF_TF_to_lig[which(SIF_TF_to_lig$Weight != 0),]
  
  ATT_TF_to_lig <- as.data.frame(run_TF_to_lig$nodesAttributes)
  colnames(ATT_TF_to_lig)[1] <- "Nodes"
  ATT_TF_to_lig$measured <- ifelse(ATT_TF_to_lig$NodeType %in% c("M","T","S","P"),1,0)
  ATT_TF_to_lig$Activity <- ATT_TF_to_lig$AvgAct
  ATT_TF_to_lig <- ATT_TF_to_lig[ATT_TF_to_lig$AvgAct != 0,]
  
  res_mofa_TF_to_lig <- list(SIF_TF_to_lig,ATT_TF_to_lig)
  save(res_mofa_TF_to_lig, file = paste0("results/cosmos/native/res_mofamoon_TF_to_lig_",cell_line,".Rdata"))
  write_csv(SIF_TF_to_lig, file = paste0("results/cosmos/native/SIF_mofamoon_TF_to_lig_",cell_line,".csv"))
  write_csv(ATT_TF_to_lig, file = paste0("results/cosmos/native/ATT_mofamoon_TF_to_lig_",cell_line,".csv"))
  
  
  combined_ATT <- as.data.frame(rbind(ATT_rec_to_TF, ATT_TF_to_lig))
  combined_ATT$sign_activity <- sign(combined_ATT$AvgAct)
  
  combined_ATT$NodeType <- ifelse(combined_ATT$NodeType == "", 0, 1) #if NodeType is available, set to 1, else set to 0
  combined_ATT <- as.data.frame(combined_ATT %>% 
                                  group_by(Nodes) %>%
                                  summarise(across(.fns= ~ mean(.x, na.rm = TRUE))))
  
  ## TF
  TF_weights <- moon_scores_native
  names(TF_weights) <- gsub("_TF","",names(TF_weights))
  TF_weights <- data.frame(Nodes = names(TF_weights), weights = TF_weights)
  
  ## Ligands
  lig_weights <- lig_rec_scores_native
  names(lig_weights) <- gsub("___.+","",names(lig_weights))
  lig_weights <- tapply(lig_weights, names(lig_weights), mean)
  ligands <- names(lig_weights)
  lig_weights <- as.numeric(lig_weights)
  names(lig_weights) <- ligands
  lig_weights <- data.frame(Nodes = names(lig_weights), weights = lig_weights)
  
  ## Receptors
  rec_weights <- lig_rec_scores_native
  names(rec_weights) <- gsub(".+___","",names(rec_weights))
  rec_weights <- tapply(rec_weights, names(rec_weights), mean)
  receptors <- names(rec_weights)
  rec_weights <- as.numeric(rec_weights)
  names(rec_weights) <- receptors
  rec_weights <- data.frame(Nodes = names(rec_weights), weights = rec_weights)
  
  ## Metabolites
  metab_weights <- data.frame(Nodes = names(metab), weights = metab)
  
  ## mOOn
  moon_weights <- ligrec_TF_moon_inputs$moon
  moon_weights <- moon_weights[!(names(moon_weights) %in% rec_weights$Nodes)]
  moon_weights <- data.frame(Nodes = names(moon_weights), weights = moon_weights)
  
  ## Combine
  feature_weights <- as.data.frame(rbind(TF_weights, rec_weights, lig_weights, metab_weights, moon_weights))
  
  ## Add weights to data
  combined_ATT <- merge(combined_ATT, feature_weights, all.x = T)
  
  ligrec_ressource <- distinct(liana::decomplexify(liana::select_resource("Consensus")[[1]]))
  ligrec_df <- ligrec_ressource[,c("source_genesymbol","target_genesymbol")]
  ligrec_df <- distinct(ligrec_df)
  names(ligrec_df) <- c("Node1","Node2")
  
  ligrec_df$Node1 <- gsub("-","_",ligrec_df$Node1)
  ligrec_df$Node2 <- gsub("-","_",ligrec_df$Node2)
  ligrec_df$Sign <- 1
  ligrec_df$Weight <- 1
  
  ligrec_df <- ligrec_df[ligrec_df$Node1 %in% combined_ATT$Nodes & ligrec_df$Node2 %in% combined_ATT$Nodes, ]
  
  combined_ATT$NodeType <- ifelse(combined_ATT$Nodes %in% ligrec_df$Node1, 2, ifelse(combined_ATT$Nodes %in% ligrec_df$Node2, 3, combined_ATT$NodeType)) #if node is a ligand set NodeType to 2, if node is a receptor set NodeType to 3, else keep 0 or 1
  
  write_csv(combined_ATT, file = paste0("results/cosmos/native/ATT_mofamoon_combined_",cell_line,".csv"))
  
  combined_SIF <- as.data.frame(rbind(SIF_rec_to_TF, SIF_TF_to_lig))
  combined_SIF <- as.data.frame(combined_SIF %>%
                                  group_by(Node1, Node2) %>%
                                  summarise(across(.fns= ~ mean(.x, na.rm = TRUE))))
  
  combined_SIF <- as.data.frame(rbind(combined_SIF,ligrec_df))
  
  res_mofa_combined <- list(combined_SIF, combined_ATT)
  save(res_mofa_combined, file = paste0("results/cosmos/native/res_mofamoon_combined_",cell_line,".Rdata"))
  write_csv(combined_SIF, file = paste0("results/cosmos/native/SIF_mofamoon_combined_",cell_line,".csv"))
  
  ligands <- combined_ATT[combined_ATT$NodeType == 2,"Nodes"] # 2 for ligand
  receptors <- combined_ATT[combined_ATT$NodeType == 3,"Nodes"] # 3 for receptors
  
  combined_SIF_reduced <- combined_SIF[!(combined_SIF$Node2 %in% receptors & !(combined_SIF$Node2 %in% combined_SIF$Node1)),] #no node that is a receptor but not a source
  combined_SIF_reduced <- combined_SIF_reduced[!(combined_SIF_reduced$Node2 %in% ligands & !(combined_SIF_reduced$Node2 %in% combined_SIF_reduced$Node1)),] #no node that is a ligand but not a source
  combined_SIF_reduced <- combined_SIF_reduced[!(combined_SIF_reduced$Node1 %in% receptors & !(combined_SIF_reduced$Node1 %in% combined_SIF_reduced$Node2)),] #no node that is a receptor but not a regulated target
  combined_SIF_reduced <- combined_SIF_reduced[!(combined_SIF_reduced$Node1 %in% ligands & !(combined_SIF_reduced$Node1 %in% combined_SIF_reduced$Node2)),] #no node that is a ligand but not a regulated target 
  
  combined_ATT_reduced <- combined_ATT[combined_ATT$Nodes %in% combined_SIF_reduced$Node1 | combined_ATT$Nodes %in% combined_SIF_reduced$Node2,]
  
  res_mofa_combined_reduced <- list(combined_SIF_reduced, combined_ATT_reduced)
  save(res_mofa_combined_reduced, file = paste0("results/cosmos/native/res_mofamoon_combined_reduced_",cell_line,".Rdata"))
  write_csv(combined_SIF_reduced, file = paste0("results/cosmos/native/SIF_mofamoon_combined_reduced_",cell_line,".csv"))
  write_csv(combined_ATT_reduced, file = paste0("results/cosmos/native/ATT_mofamoon_combined_reduced_",cell_line,".csv"))
}
```

## Visualize native COSMOS network

Further, as performed in the RCytoScape tutorial with the MOFA-COSMOS network, we visualize our native network with CytoScape.

```{r CytoScape, eval=FALSE}

## Visualization

interesting_nodes <- data.frame("name" = c("CCNA2","EGFR", "FOS", "HRAS",  "JUN", "MAP2K1", "MAP2K2", "MAPK1", "MAPK3", "MYC",  "NFKB1", "PCNA", "RAF1", "STAT3", "TGFB1", "THBS1", "VEGFA"))

style.name = "dataStyle_cosmos_native"
createVisualStyle(style.name)

for (cell_line in c("SF-539", "MOLT-4")) {
  
  load(file = paste0("results/cosmos/native/res_mofamoon_combined_reduced_",cell_line,".Rdata"))
  combined_ATT_reduced <- res_mofa_combined_reduced[[2]]
  combined_SIF_reduced <- res_mofa_combined_reduced[[1]]
  
  nodes <- data.frame(id = combined_ATT_reduced$Nodes, NodeType = as.integer(combined_ATT_reduced$NodeType), Activity = combined_ATT_reduced$Activity, weights = as.numeric(combined_ATT_reduced$weights), stringsAsFactors = F)
  nodes$weights[is.na(nodes$weights)] <- 0
  
  edges <- data.frame(source=combined_SIF_reduced$Node1, target = combined_SIF_reduced$Node2, sign = combined_SIF_reduced$Sign, weight = combined_SIF_reduced$Weight,stringsAsFactors = F)
  
  createNetworkFromDataFrames(nodes,edges,title = paste0("Full COSMOS native network ", cell_line), table.key.column = "name", collection = paste0("Full Network ", cell_line))
  setVisualStyle(style.name, network = paste0("Full COSMOS native network ", cell_line))
  
  setEdgeTargetArrowShapeMapping(table.column = "sign",table.column.values = list("-1","1"), shapes = list("T","ARROW"), style.name = style.name, network = paste0("Full COSMOS native network ", cell_line))
  setEdgeLineWidthDefault(2, style.name)
  
  duplicated_edges <- as.data.frame(getTableColumns('edge','sign', network = paste0("Full COSMOS native network ", cell_line)))
  duplicated_edges[,2] <- rownames(duplicated_edges)
  duplicated_edges <- duplicated_edges[is.na(duplicated_edges$sign),2]
  selectEdges(duplicated_edges, network = paste0("Full COSMOS native network ", cell_line))
  deleteSelectedEdges(network = paste0("Full COSMOS native network ", cell_line))
  
  setNodeShapeDefault("ROUND_RECTANGLE", style.name) #remember to specify your style.name!
  setNodeShapeMapping(table.column = "NodeType", table.column.values = list("1","2","3"),shapes = list("Octagon","VEE","Triangle"), style.name = style.name, network = paste0("Full COSMOS native network ", cell_line))
  setNodeColorDefault("#89D0F5", style.name)
  setNodeLabelMapping("name", style.name, network = paste0("Full COSMOS native network ", cell_line))
  setNodeHeightDefault(35,style.name)
  setNodeFontSizeDefault(12,style.name)
  setNodeWidthDefault(75,style.name)
  setNodeBorderWidthDefault(12, style.name = style.name)

  #Set node and border color based on data min and max values (weights, cosmos weights)
  native_weights = getTableColumns('node','weights', network = paste0("Full COSMOS native network ", cell_line))
  native_weights_min = min(native_weights[,1],na.rm=TRUE)
  native_weights_max = max(native_weights[,1],na.rm=TRUE)
  native_data.values = c(native_weights_min,0,native_weights_max)
  border.colors <- c(rev(brewer.pal(length(native_data.values), "RdBu")))
  setNodeBorderColorMapping('weights', native_data.values, border.colors, style.name = style.name, network = paste0("Full COSMOS native network ", cell_line))
  
  cosmos_weights = getTableColumns('node','Activity', network = paste0("Full COSMOS native network ", cell_line))
  cosmos_weights_min = min(cosmos_weights[,1],na.rm=TRUE)
  cosmos_weights_max = max(cosmos_weights[,1],na.rm=TRUE)
  cosmos_data.values = c(cosmos_weights_min,0,cosmos_weights_max)
  node.colors <- c(rev(brewer.pal(length(cosmos_data.values), "RdBu")))
  setNodeColorMapping('Activity',cosmos_data.values, node.colors, style.name = style.name, network = paste0("Full COSMOS native network ", cell_line))
}

style.name = "dataStyle_cosmos_native_MAPK_pathway"
createVisualStyle(style.name)

for (cell_line in c("SF-539", "MOLT-4")) { 
  
  load(file = paste0("results/cosmos/native/res_mofamoon_combined_reduced_",cell_line,".Rdata"))
  
  combined_ATT_reduced <- res_mofa_combined_reduced[[2]]
  combined_SIF_reduced <- res_mofa_combined_reduced[[1]]
  
  nodes <- data.frame(id = combined_ATT_reduced$Nodes, NodeType = as.integer(combined_ATT_reduced$NodeType), Activity = combined_ATT_reduced$Activity, weights = as.numeric(combined_ATT_reduced$weights), stringsAsFactors = F)
  nodes$weights[is.na(nodes$weights)] <- 0
  
  edges <- data.frame(source=combined_SIF_reduced$Node1, target = combined_SIF_reduced$Node2, sign = combined_SIF_reduced$Sign, weight = combined_SIF_reduced$Weight,stringsAsFactors = F)
  
  ##https://www.genome.jp/entry/N00001
  EGF_EGFR_RAS_ERK_pathway_extended <- c("EGF", "EGFR", "GRB2", "SOS1", "SOS2", "HRAS", "KRAS", "NRAS", "ARAF", "BRAF", "RAF1", "MAP2K1", "MAP2K2", "MAPK1", "MAPK3", "CCND1", "CREBBP", "MYC", "SRF", "FOS")
  
  edges_MAPK_reduced_selected <- edges[edges$target %in% EGF_EGFR_RAS_ERK_pathway_extended & edges$source %in% EGF_EGFR_RAS_ERK_pathway_extended,]
  
  edges_MAPK_reduced_selected_start_end <- rbind(edges_MAPK_reduced_selected, edges[edges$target %in% "EGFR",],edges[edges$source %in% c("FOS","MYC"),])
  
  nodes_MAPK_reduced_selected_start_end <- nodes[nodes$id %in% edges_MAPK_reduced_selected_start_end$source | nodes$id %in% edges_MAPK_reduced_selected_start_end$target,]
  
  createNetworkFromDataFrames(nodes_MAPK_reduced_selected_start_end,edges_MAPK_reduced_selected_start_end,title = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line), table.key.column = "name", collection = paste0("Sub-Network ", cell_line))
  setVisualStyle(style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  
  remove_nodes <- getAllNodes(network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  remove_nodes <- remove_nodes[!(remove_nodes %in% interesting_nodes$name)]
  remove_nodes <- lapply(remove_nodes, function(x) x)
  selectNodes(remove_nodes, by.col = "name", network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  deleteSelectedNodes(network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  
  setEdgeTargetArrowShapeMapping(table.column = "sign",table.column.values =  list("-1","1"), shapes = list("T","ARROW"), style.name = style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  setEdgeLineWidthDefault(2, style.name)
  setNodeShapeDefault("ROUND_RECTANGLE", style.name) 
  setNodeShapeMapping(table.column = "NodeType", table.column.values = list("1","2","3"),shapes = list("Octagon","VEE","Triangle"), style.name = style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  setNodeColorDefault("#89D0F5", style.name)
  setNodeLabelMapping("name", style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  setNodeHeightDefault(35,style.name)
  setNodeFontSizeDefault(12,style.name)
  setNodeWidthDefault(75,style.name)
  setNodeBorderWidthDefault(12, style.name = style.name)

  #Set node and border color based on data min and max values (weights, cosmos weights)
  native_weights = getTableColumns('node','weights', network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  native_weights_min = min(native_weights[,1],na.rm=TRUE)
  native_weights_max = max(native_weights[,1],na.rm=TRUE)
  native_data.values = c(native_weights_min,0,native_weights_max)
  border.colors <- c(rev(brewer.pal(length(native_data.values), "RdBu")))
  setNodeBorderColorMapping('weights', native_data.values, border.colors, style.name = style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  
  cosmos_weights = getTableColumns('node','Activity', network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
  cosmos_weights_min = min(cosmos_weights[,1],na.rm=TRUE)
  cosmos_weights_max = max(cosmos_weights[,1],na.rm=TRUE)
  cosmos_data.values = c(cosmos_weights_min,0,cosmos_weights_max)
  node.colors <- c(rev(brewer.pal(length(cosmos_data.values), "RdBu")))
  setNodeColorMapping('Activity',cosmos_data.values, node.colors, style.name = style.name, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
}
```

```{r, eval=FALSE}
for (cell_line in c("SF-539", "MOLT-4")) {
  exportImage(filename = paste0("results/cytoscape/full_network_cosmos_native_", cell_line), type = "PDF", resolution = 900, network =  paste0("Full COSMOS native network ", cell_line))
  exportImage(filename = paste0("results/cytoscape/subnetwork_EGF_EGFR_RAS_ERK_pathway_extended_cosmos_native_", cell_line), type = "PDF", resolution = 900, network = paste0("Native COSMOS EGF_EGFR_RAS_ERK_pathway_start_end ", cell_line))
}  

saveSession(filename = "results/cytoscape/cosmos_native_network_analysis.cys")
```


## Session info

```{r Session info}
sessionInfo()
```



